### ISSUE TITLE
URL encoded strings not working on android

### ISSUE THREAD

**Issue by saulshanabrook** [shripalsoni04/nativescript-webview-interface#9]
If you URL encode a `"` and try to send that as a message, it is not quoted properly on android.

You can see an example repo with this problem https://github.com/saulshanabrook/nativescript-webview-interface-demo. If you click "Add", you will see this error in the webview. 

This PR will fix this issue https://github.com/shripalsoni04/nativescript-webview-interface/pull/6

**Comment by shripalsoni04** [comment]
PR #6 is already merged with the source code and available since 1.3.2. Is this issue still coming?

**Comment by saulshanabrook** [comment]
@shripalsoni04 I think you addressed this problem previously by not using `encodeURIComponent` and instead just `JSON.stringify`. I think this works for `"` but not for some other symbols... For example, this test repo I pointed to will fail, with this commit https://github.com/saulshanabrook/nativescript-webview-interface-demo/commit/cab4bcd1c0b80ca06ca875c127fb4395bdd93796

**Comment by shripalsoni04** [comment]
@saulshanabrook In that case, I will prefer not to use `encodeURIComponent` in this plugin itself because it will increase the payload size of the data getting exchanged between native and webview and android has some limits on the size. So if we add that in plugin, it may fail for others who are exchanging large data like image dataURI

Due to this reason, I will suggest you to encode/decode the string with special characters at your code level and then exchange that encoded data using this plugin.

Hope this will help you.
